# Generated by Django 6.0.1 on 2026-02-07 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='photo',
            new_name='flags',
        ),
    ]
