# Generated by Django 6.0.1 on 2026-02-07 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country_app', '0002_rename_photo_country_flags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
    ]
