services:
  backend:
    build:
      context: ./backend
    ports:
      - "5555:5555"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1

  frontend:
    build:
      context: ./frontend
    ports:
      - "3333:3333"
    volumes:
      - ./frontend:/app
      - /app/node_modules